// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace T4Template
{
using System;   

	public class TestClass
	{
	   public static void HelloWorld()
	   {
		  Console.WriteLine("Hello, world!");
	   }
	}
}
